### ISSUE TITLE
What is the OpenGL version that's supported

### ISSUE THREAD

**Issue by LegacyGamerHD** [luo9674/VGPU#1]

**Comment by LegacyGamerHD** [comment]
Also what does this

**Comment by luo9674** [comment]
For the time being, it's a buggy version of OpenGL 3. 0, which calls gles3 by default.

**Comment by luo9674** [comment]
Of course it can't be used to render graphics right now, I'm dealing with texturing issues.

**Comment by rscAvePlex** [comment]
😃
